name: Build rock

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  pull_request:
  workflow_call:
    outputs:
      rock:
        description: "The rock output of build process."
        value: ${{ jobs.build.outputs.rock }}

jobs:
  lint:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Install tox
        run: python3 -m pip install tox
      - name: YAML Lint
        run: tox -e lint

  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    needs:
      - lint
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup LXD
        uses: canonical/setup-lxd@main
      - name: Install dependencies
        id: install
        run: |
          sudo snap install yq
          sudo snap install rockcraft --classic --edge
      - name: Build rock
        id: build
        run: |
          VERSION=$(yq '.version' rockcraft.yaml)

          rockcraft pack --verbose

          echo "rock=zookeeper_${VERSION}_amd64.rock" >> $GITHUB_OUTPUT

      - name: Upload locally built rock artifact
        uses: actions/upload-artifact@v3
        with:
          name: zookeeper
          path: ${{ steps.build.outputs.rock }}
    outputs:
      rock: ${{ steps.build.outputs.rock }}

  test:
    name: Test Image
    runs-on: ubuntu-latest
    timeout-minutes: 60
    needs: build
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Install skopeo
        run: |
          sudo snap install --devmode --channel edge skopeo
      - uses: actions/download-artifact@v3
        with:
          name: zookeeper
      - name: Test Image
        run: |

          sudo skopeo --insecure-policy copy \
            oci-archive:${{ needs.build.outputs.rock }} \
            docker-daemon:zookeeper:latest

          docker run -d -p 2181:2181 zookeeper:latest

          sleep 10 
          CHECK=$(echo srvr | nc localhost 2181 | grep "Mode" | wc -l)
       
          if [[ $CHECK != 1 ]]; 
          then 
            echo "Zookeeper service possibly not running"
            exit 1; 
          else
            echo "Zookeeper service up and running!"
          fi 
